name: posible
description: POSible - sistema de punto de venta (POS) con inventario, reportes, clientes y lealtad.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.2
  mobile_scanner: ^7.4.0
  http: ^1.2.2
  image_picker: ^1.1.2
  csv: ^8.0.0
  share_plus: ^13.3.0
  file_picker: ^12.0.0
  audioplayers: ^6.8.1
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/beep.wav
